### ISSUE TITLE
Overall last updated date always says “Invalid Date”

### ISSUE THREAD

**Issue by R0GGER** [karimsa/patrol#15]
I have set "interval: 60s" but the last check has been a few minutes ago... 
Do I have to create a cron task to check every minute? How does this work?

Please you help.

**Comment by karimsa** [comment]
Thanks for trying out patrol!

I'll have a look at this for you. Would you be able to share your docker logs for the container? (i.e. `docker logs patrol > patrol.log` and then upload `patrol.log`)

**Comment by R0GGER** [comment]
Sorry I can't... I already removed it. 

I had a few issues:
- Not sure when it was checking ("interval: 60s"), time in (top right) Last updated: Invalid.
- No timezone settings
- I was unsure how much time a grey, green, yellow or red bar was... 1 day or 60 seconds?
- Ping wasn't working
- Curl command sometimes not working with certain websites.

**Comment by R0GGER** [comment]
Last updated: Invalid date
![image](https://user-images.githubusercontent.com/8298741/87639364-72263980-c745-11ea-9c89-c0a0aaa1d1f2.png)

**Comment by karimsa** [comment]
Sorry, that's definitely a bug! If you look at the individual services though, you'll see the most accurate timestamp (in this case, "a few seconds ago"). I'll look into fixing this.

I can open a feature request for you regarding the timezone support, as well as for the timespan of downtimes.

Can you please provide what the errors were with ping/curl? And what containers you were using for those?

**Comment by R0GGER** [comment]
Hmm... maybe it's just a documentation issue! 
Solved the issue with CURL and PING. I was using the wrong commands, my bad!

**Curl:**
`cmd: 'curl -sSLk /dev/null [host]'`
k = no certificate validation.

**Ping:** 
`cmd: 'ping -c1 [host] >/dev/null'`

**Comment by karimsa** [comment]
This has been fixed in `v1`. Sorry for the long wait. If you are still using patrol, I'd love to hear your thoughts on v1!
