### ISSUE TITLE
Build for arm/v7?

### ISSUE THREAD

**Issue by madrhr** [karimsa/patrol#38]
Hi everyone,

great work so far. Just wondering if there is a build or workaround to make this docker container running for arm/v7?

Error message is:
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

So the container is starting but then immediately crashing.

Thanks in advance if anyone has a solution :)

**Comment by karimsa** [comment]
Hey! Thanks for opening the issue. We currently have armv8 images, but not armv7. Just out of curiosity: what arm v7 devices are you running patrol on?

I think arm v7 support must be similar to add to arm v8, it is something I can look into. If you would like to PR, I'm also open to contributions.

**Comment by madrhr** [comment]
Hi, thanks for the quick answer.
I'm running a Raspberry PI OS 32-bit (Debian version: 11 (bullseye)) on my Raspberry PI 4 B 4GB RAM.
I think i found out that i must have accidentally installed a 32-bit version but now i have a lot of containers and other stuff running which i dont want to configure from the start again.

Unfortunately i also havent worked with Go ever, so i dont think i can provide a PR.

**Comment by karimsa** [comment]
No worries. I didn’t realize there’s still 32bit RPis out there! I’ll have a look sometime this week for you

**Comment by madrhr** [comment]
Yeah, it was my bad. But i would be very grateful if you could have a look. Thanks

**Comment by karimsa** [comment]
Hey, @mrcldrhr - did you close this issue because you no longer need the arm v7 build?

**Comment by madrhr** [comment]
Yes, but thank you anyways.
